In [535]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [537]:
df=pd.read_excel(r"C:\Users\MT-Team\Downloads\Employee Sample Data - A.xlsx")

In [539]:
data=pd.DataFrame(df)

In [541]:
print(data)

       EEID        Full Name                 Job Title  Department  \
0    E02387      Emily Davis                Sr. Manger          IT
1    E04105    Theodore Dinh       Technical Architect          IT
2    E02572     Luna Sanders                  Director     Finance
3    E02832  Penelope Jordan  Computer Systems Manager          IT
4    E01639        Austin Vo               Sr. Analyst     Finance
..      ...              ...                       ...         ...
987  E03094     Wesley Young               Sr. Analyst   Marketing
988  E01909     Lillian Khan                   Analyst     Finance
989  E04398      Oliver Yang                  Director   Marketing
990  E02521      Lily Nguyen               Sr. Analyst     Finance
991  E03545      Sofia Cheng            Vice President  Accounting

              Business Unit  Gender  Ethnicity   Age  Hire Date  \
0    Research & Development  Female      Black  55.0 2016-04-08
1             Manufacturing    Male      Asian  59.0 1997-11-29
2       Speciality Products  Female  Caucasian  50.0 2006-10-26
3             Manufacturing  Female  Caucasian  26.0 2019-09-27
4             Manufacturing    Male      Asian  55.0 1995-11-20
..                      ...     ...        ...   ...        ...
987     Speciality Products    Male  Caucasian  33.0 2016-09-18
988     Speciality Products  Female      Asian  44.0 2010-05-31
989     Speciality Products    Male      Asian  31.0 2019-06-10
990     Speciality Products  Female      Asian  33.0 2012-01-28
991               Corporate  Female      Asian  63.0 2020-07-26

     Annual Salary  Bonus %        Country       City  Exit Date
0         141604.0     0.15  United States    Seattle 2021-10-16
1          99975.0     0.00          China  Chongqing        NaT
2         163099.0     0.20  United States    Chicago        NaT
3          84913.0     0.07  United States    Chicago        NaT
4          95409.0     0.00  United States    Phoenix        NaT
..             ...      ...            ...        ...        ...
987        98427.0     0.00  United States   Columbus        NaT
988        47387.0     0.00          China    Chengdu 2018-01-08
989       176710.0     0.15  United States      Miami        NaT
990        95960.0     0.00          China    Chengdu        NaT
991       216195.0     0.31  United States      Miami        NaT

[992 rows x 14 columns]

In [542]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           992 non-null    object
 1   Full Name      992 non-null    object
 2   Job Title      991 non-null    object
 3   Department     990 non-null    object
 4   Business Unit  992 non-null    object
 5   Gender         991 non-null    object
 6   Ethnicity      985 non-null    object
 7   Age            986 non-null    float64
 8   Hire Date      985 non-null    datetime64[ns]
 9   Annual Salary  981 non-null    float64
 10  Bonus %        984 non-null    float64
 11  Country        990 non-null    object
 12  City           990 non-null    object
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(3), object(9)
memory usage: 108.6+ KB

In [547]:
df.isnull().sum()

EEID               0
Full Name          0
Job Title          1
Department         2
Business Unit      0
Gender             1
Ethnicity          7
Age                6
Hire Date          7
Annual Salary     11
Bonus %            8
Country            2
City               2
Exit Date        907
dtype: int64

In [549]:
df[df["Age"].isnull()]

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
45,E03538,Gabriel Holmes,Enterprise Architect,IT,Research & Development,Male,Caucasian,NaN,2010-11-04,92952.0,0.0,United States,Seattle,NaT
142,E03717,Joseph Ruiz,Field Engineer,Engineering,Manufacturing,Male,NaN,NaN,NaT,NaN,NaN,Brazil,Sao Paulo,NaT
143,E01533,Avery Bailey,Sr. Analyst,Sales,Speciality Products,Female,NaN,NaN,NaT,NaN,NaN,United States,Phoenix,NaT
144,E04449,Miles Hsu,Analyst II,Finance,Research & Development,Male,NaN,NaN,NaT,NaN,NaN,China,Chengdu,NaT
145,E02855,Piper Cheng,Enterprise Architect,IT,Manufacturing,Female,NaN,NaN,NaT,NaN,NaN,United States,Miami,NaT
146,E00816,Skylar Watson,Network Architect,IT,Speciality Products,Female,NaN,NaN,NaT,NaN,NaN,United States,Phoenix,NaT

In [551]:
x=df["Age"].mean()

In [553]:
df=df.fillna({"Age":x})

In [555]:
df['Bonus %'] = df.groupby('Job Title')['Bonus %'].transform(
    lambda x: x.fillna(x.median())
)

In [557]:
df['Annual Salary'] = df.groupby('Job Title')['Annual Salary'].transform(
    lambda x: x.fillna(x.median())
)

In [559]:
df[df["Hire Date"].isnull()]

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
115,E02017,Connor Joseph,Director,Human Resources,Corporate,Male,Caucasian,50.000000,NaT,171173.0,0.23,NaN,NaN,NaT
130,E03131,Ezekiel Reed,Sr. Manger,IT,Manufacturing,Male,Caucasian,37.000000,NaT,142108.5,0.12,NaN,NaN,2021-05-01
142,E03717,Joseph Ruiz,Field Engineer,Engineering,Manufacturing,Male,NaN,44.348884,NaT,74628.5,0.00,Brazil,Sao Paulo,NaT
143,E01533,Avery Bailey,Sr. Analyst,Sales,Speciality Products,Female,NaN,44.348884,NaT,89390.0,0.00,United States,Phoenix,NaT
144,E04449,Miles Hsu,Analyst II,Finance,Research & Development,Male,NaN,44.348884,NaT,61313.0,0.00,China,Chengdu,NaT
145,E02855,Piper Cheng,Enterprise Architect,IT,Manufacturing,Female,NaN,44.348884,NaT,88777.0,0.00,United States,Miami,NaT
146,E00816,Skylar Watson,Network Architect,IT,Speciality Products,Female,NaN,44.348884,NaT,86831.0,0.00,United States,Phoenix,NaT

In [560]:
df=df.drop(df.index[[115,130,142,143,144]])

In [561]:
df['Is Active'] = df['Exit Date'].isnull()

In [562]:
df.head(5)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Is Active
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55.0,2016-04-08,141604.0,0.15,United States,Seattle,2021-10-16,False
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59.0,1997-11-29,99975.0,0.00,China,Chongqing,NaT,True
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50.0,2006-10-26,163099.0,0.20,United States,Chicago,NaT,True
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26.0,2019-09-27,84913.0,0.07,United States,Chicago,NaT,True
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55.0,1995-11-20,95409.0,0.00,United States,Phoenix,NaT,True

In [563]:
df.isnull().sum()

EEID               0
Full Name          0
Job Title          1
Department         2
Business Unit      0
Gender             1
Ethnicity          4
Age                0
Hire Date          2
Annual Salary      1
Bonus %            1
Country            0
City               0
Exit Date        903
Is Active          0
dtype: int64

In [569]:
df = df[df.drop(columns=['Exit Date']).notnull().all(axis=1)]

In [571]:
df.isnull().sum()

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        896
Is Active          0
dtype: int64

In [573]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 980 entries, 0 to 991
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           980 non-null    object
 1   Full Name      980 non-null    object
 2   Job Title      980 non-null    object
 3   Department     980 non-null    object
 4   Business Unit  980 non-null    object
 5   Gender         980 non-null    object
 6   Ethnicity      980 non-null    object
 7   Age            980 non-null    float64
 8   Hire Date      980 non-null    datetime64[ns]
 9   Annual Salary  980 non-null    float64
 10  Bonus %        980 non-null    float64
 11  Country        980 non-null    object
 12  City           980 non-null    object
 13  Exit Date      84 non-null     datetime64[ns]
 14  Is Active      980 non-null    bool
dtypes: bool(1), datetime64[ns](2), float64(3), object(9)
memory usage: 115.8+ KB

In [676]:
df.loc[0,"EEID"]=1
df.loc[1,"EEID"]=2
df.loc[2,"EEID"]=3
df.loc[3,"EEID"]=4
df.loc[4,"EEID"]=5

In [577]:
df.loc[0,"Full Name"]="X"
df.loc[1,"Full Name"]="Y"
df.loc[2,"Full Name"]="W"
df.loc[3,"Full Name"]="Z"
df.loc[4,"Full Name"]="O"

In [678]:
df.loc[0,"Job Title"]="A"
df.loc[1,"Job Title"]="B"
df.loc[2,"Job Title"]="C"
df.loc[3,"Job Title"]="D"
df.loc[4,"Job Title"]="E"

In [581]:
df.loc[0,"Department"]="00"
df.loc[1,"Department"]="01"
df.loc[2,"Department"]="02"
df.loc[3,"Department"]="03"
df.loc[4,"Department"]="04"

In [583]:
df.loc[0,"Business Unit"]="000"
df.loc[1,"Business Unit"]="001"
df.loc[2,"Business Unit"]="002"
df.loc[3,"Business Unit"]="003"
df.loc[4,"Business Unit"]="004"

In [585]:
df.loc[0,"Gender"]="F"
df.loc[1,"Gender"]="M"
df.loc[2,"Gender"]="F"
df.loc[3,"Gender"]="F"
df.loc[4,"Gender"]="M"

In [587]:
df.loc[0,"Ethnicity"]="B"
df.loc[1,"Ethnicity"]="A"
df.loc[2,"Ethnicity"]="C"
df.loc[3,"Ethnicity"]="C"
df.loc[4,"Ethnicity"]="A"

In [680]:
df.loc[0, "Hire Date"] = pd.to_datetime("2020-03-02")
df.loc[1,"Hire Date"]=pd.to_datetime("2021-06-09")
df.loc[2,"Hire Date"]=pd.to_datetime("2019-11-26")
df.loc[3,"Hire Date"]=pd.to_datetime("2017-01-08")
df.loc[4,"Hire Date"]=pd.to_datetime("2010-11-26")

In [682]:
df.loc[0,"Age"]=20
df.loc[1,"Age"]=30
df.loc[2,"Age"]=2
df.loc[3,"Age"]=36
df.loc[4,"Age"]=37

In [684]:
df1.loc[0,"Annual Salary"]=200
df1.loc[1,"Annual Salary"]=300
df1.loc[2,"Annual Salary"]=220
df1.loc[3,"Annual Salary"]=360
df1.loc[4,"Annual Salary"]=370

In [686]:
df1.loc[0,"Bonus %"]=0.330
df1.loc[1,"Bonus %"]=0.300
df1.loc[2,"Bonus %"]=0.220
df1.loc[3,"Bonus %"]=0.360
df1.loc[4,"Bonus %"]=0.370

In [688]:

df1.loc[0,"Country"]="US"
df1.loc[1,"Country"]="UAE"
df1.loc[2,"Country"]="US"
df1.loc[3,"Country"]="UK"
df1.loc[4,"Country"]="UAE"

In [690]:
df1.loc[0,"City"]="A"
df1.loc[1,"City"]="B"
df1.loc[2,"City"]="A"
df1.loc[3,"City"]="O"
df1.loc[4,"City"]="L"

In [692]:
df1.loc[0,"Exit Date"]=pd.to_datetime("2015-07-30")
df1.loc[1,"Exit Date"]=pd.to_datetime("2009-02-07")
df1.loc[2,"Exit Date"]=pd.to_datetime("2019-09-29")
df1.loc[3,"Exit Date"]=pd.to_datetime("2023-11-07")
df1.loc[4,"Exit Date"]=pd.to_datetime("2006-02-25")

In [694]:
df1.loc[0,"Is Active"]=0
df1.loc[1,"Is Active"]=1
df1.loc[2,"Is Active"]=0
df1.loc[3,"Is Active"]=0
df1.loc[4,"Is Active"]=1

In [696]:
df1.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Is Active
0,1,X,A,00,000,F,B,55.0,2020-03-02,200.0,0.33,US,A,2015-07-30,0.0
1,2,Y,B,01,001,M,A,30.0,2021-06-09,300.0,0.30,UAE,B,2009-02-07,1.0
2,3,W,C,02,002,F,C,2.0,2019-11-26,220.0,0.22,US,A,2019-09-29,0.0
3,4,Z,D,03,003,F,C,36.0,2017-01-08,360.0,0.36,UK,O,2023-11-07,0.0
4,5,O,E,04,004,M,A,37.0,2010-11-26,370.0,0.37,UAE,L,2006-02-25,1.0

In [698]:
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Is Active
0,1,Emily Davis,A,IT,Research & Development,Female,Black,20.0,2020-03-02,141604.0,0.15,United States,Seattle,2021-10-16,False
1,2,Theodore Dinh,B,IT,Manufacturing,Male,Asian,30.0,2021-06-09,99975.0,0.00,China,Chongqing,NaT,True
2,3,Luna Sanders,C,Finance,Speciality Products,Female,Caucasian,2.0,2019-11-26,163099.0,0.20,United States,Chicago,NaT,True
3,4,Penelope Jordan,D,IT,Manufacturing,Female,Caucasian,36.0,2017-01-08,84913.0,0.07,United States,Chicago,NaT,True
4,5,Austin Vo,E,Finance,Manufacturing,Male,Asian,37.0,2010-11-26,95409.0,0.00,United States,Phoenix,NaT,True

In [700]:
x=df["Annual Salary"].max()
df[df["Annual Salary"]==x]

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Is Active
981,E04354,Raelynn Rios,Vice President,Sales,Manufacturing,Female,Latino,43.0,2016-08-21,258498.0,0.35,United States,Columbus,NaT,True

In [702]:
df.groupby("Department")[["Age","Annual Salary"]].mean()

                       Age  Annual Salary
Department
Accounting       43.656250  123146.947917
Engineering      45.858065  108490.441935
Finance          44.470085  123447.470085
Human Resources  44.173554  117282.607438
IT               44.001497   97820.618026
Marketing        43.216667  129663.033333
Sales            43.586957  110946.449275

In [703]:
df.groupby(["Department","Ethnicity"])["Age"].max()

Department       Ethnicity
Accounting       Asian        64.0
                 Black        51.0
                 Caucasian    62.0
                 Latino       62.0
Engineering      Asian        65.0
                 Black        56.0
                 Caucasian    64.0
                 Latino       64.0
Finance          Asian        64.0
                 Black        65.0
                 Caucasian    64.0
                 Latino       65.0
Human Resources  Asian        64.0
                 Black        55.0
                 Caucasian    64.0
                 Latino       65.0
IT               Asian        65.0
                 Black        61.0
                 Caucasian    65.0
                 Latino       64.0
Marketing        Asian        65.0
                 Black        65.0
                 Caucasian    65.0
                 Latino       65.0
Sales            Asian        64.0
                 Black        65.0
                 Caucasian    63.0
                 Latino       61.0
Name: Age, dtype: float64

In [668]:
df.groupby(["Department","Ethnicity"])["Age"].min()

Department       Ethnicity
Accounting       Asian        25.0
                 Black        30.0
                 Caucasian    26.0
                 Latino       26.0
Engineering      Asian        25.0
                 Black        27.0
                 Caucasian    25.0
                 Latino       27.0
Finance          Asian        25.0
                 Black        25.0
                 Caucasian    25.0
                 Latino       25.0
Human Resources  Asian        25.0
                 Black        25.0
                 Caucasian    26.0
                 Latino       29.0
IT               Asian        25.0
                 Black        28.0
                 Caucasian    26.0
                 Latino       25.0
Marketing        Asian        25.0
                 Black        27.0
                 Caucasian    25.0
                 Latino       29.0
Sales            Asian        25.0
                 Black        26.0
                 Caucasian    26.0
                 Latino       26.0
Name: Age, dtype: float64

In [672]:
df.groupby(["Department","Ethnicity"])["Age"].mean()

Department       Ethnicity
Accounting       Asian        45.121951
                 Black        37.333333
                 Caucasian    42.406250
                 Latino       43.600000
Engineering      Asian        46.946429
                 Black        42.142857
                 Caucasian    45.833333
                 Latino       45.180000
Finance          Asian        47.408163
                 Black        48.000000
                 Caucasian    42.407407
                 Latino       42.781250
Human Resources  Asian        43.583333
                 Black        40.307692
                 Caucasian    45.296296
                 Latino       45.636364
IT               Asian        43.766667
                 Black        42.650000
                 Caucasian    45.807731
                 Latino       43.500000
Marketing        Asian        45.400000
                 Black        42.500000
                 Caucasian    40.636364
                 Latino       42.000000
Sales            Asian        43.775862
                 Black        45.461538
                 Caucasian    41.100000
                 Latino       44.648649
Name: Age, dtype: float64

In [674]:
df.groupby(["Department","Ethnicity"])["Annual Salary"].median()

Department       Ethnicity
Accounting       Asian        114893.0
                 Black         91853.0
                 Caucasian    121159.5
                 Latino        92317.0
Engineering      Asian         91230.0
                 Black         74412.0
                 Caucasian     93630.0
                 Latino        96818.0
Finance          Asian        124928.0
                 Black        131652.0
                 Caucasian    102847.0
                 Latino       124553.0
Human Resources  Asian        123233.5
                 Black        142318.0
                 Caucasian    104162.0
                 Latino       101985.0
IT               Asian         90652.5
                 Black         74834.5
                 Caucasian     81218.0
                 Latino        83403.0
Marketing        Asian        147752.0
                 Black         86075.5
                 Caucasian    113135.0
                 Latino        97063.5
Sales            Asian         89528.5
                 Black         94246.0
                 Caucasian     92930.5
                 Latino       113269.0
Name: Annual Salary, dtype: float64

In [707]:
df.to_excel(r"C:\Users\MT-Team\Desktop\Training\Employee Sample Data_clean - A.xlsx")